version: "3.7"

services:
  backend:
    image: registry.alpinelinux.org/alpine/infra/build-server-status:latest
    ports:
      - 8033:8080
  frontend:
    image: nginx:mainline-alpine
    volumes:
      - ./index.html:/var/www/index.html
      - ./js:/var/www/js
      - ./css:/var/www/css
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8032:80
